# Generated by Django 5.2.16 on 2026-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habbits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='habbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='habit',
        ),
    ]
