# Generated by Django 5.2.16 on 2026-08-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habbits', '0002_habbit_delete_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habbit',
            name='file',
        ),
    ]
