# Generated by Django 5.2.16 on 2026-08-07 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habbits', '0003_remove_habbit_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabbitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField(auto_now_add=True)),
                ('habbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habbits.habbit')),
            ],
        ),
    ]
