# Generated by Django 5.2.16 on 2026-08-07 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habbits', '0004_habbitlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habbitlog',
            name='habbit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habbits.habbit'),
        ),
        migrations.AddConstraint(
            model_name='habbitlog',
            constraint=models.UniqueConstraint(fields=('habbit', 'completed_on'), name='unique_habit_per_day'),
        ),
    ]
